ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=4)

      DOUBLE PRECISION MDL_MT,MDL_MW,MDL_MZ,MDL_MTA,MDL_MB,MDL_MH

      COMMON/MASSES/ MDL_MT,MDL_MW,MDL_MZ,MDL_MTA,MDL_MB,MDL_MH


      DOUBLE PRECISION MDL_WZ,MDL_WH,MDL_WW,MDL_WT

      COMMON/WIDTHS/ MDL_WZ,MDL_WH,MDL_WW,MDL_WT


      DOUBLE COMPLEX GC_2, GC_3, GC_574, GC_575, GC_580, GC_581,
     $  GC_599, GC_600, GC_618, GC_619, GC_644, GC_645, GC_698, GC_699
     $ , GC_815, GC_825, GC_315, GC_316, GC_317, GC_318, GC_319,
     $  GC_321, GC_516, GC_522, GC_536, GC_543

      COMMON/COUPLINGS/ GC_2, GC_3, GC_574, GC_575, GC_580, GC_581,
     $  GC_599, GC_600, GC_618, GC_619, GC_644, GC_645, GC_698, GC_699
     $ , GC_815, GC_825, GC_315, GC_316, GC_317, GC_318, GC_319,
     $  GC_321, GC_516, GC_522, GC_536, GC_543

