ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      SUBROUTINE COUP1()

      IMPLICIT NONE
      INCLUDE 'model_functions.inc'

      DOUBLE PRECISION PI, ZERO
      PARAMETER  (PI=3.141592653589793D0)
      PARAMETER  (ZERO=0D0)
      INCLUDE 'input.inc'
      INCLUDE 'coupl.inc'
      GC_2 = (2.000000D+00*MDL_EE*MDL_COMPLEXI)/3.000000D+00
      GC_3 = -(MDL_EE*MDL_COMPLEXI)
      GC_574 = -(MDL_CW*MDL_EE*MDL_COMPLEXI)/(2.000000D+00*MDL_SW)
      GC_575 = (MDL_CW*MDL_EE*MDL_COMPLEXI)/(2.000000D+00*MDL_SW)
      GC_580 = -(MDL_EE*MDL_COMPLEXI*MDL_SW)/(6.000000D+00*MDL_CW)
      GC_581 = (MDL_EE*MDL_COMPLEXI*MDL_SW)/(2.000000D+00*MDL_CW)
      GC_599 = (MDL_CTZ*MDL_COMPLEXI*MDL_VEV)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2)
      GC_600 = (MDL_CTZI*MDL_VEV)/(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
      GC_698 = (MDL_CTW*MDL_COMPLEXI*MDL_VEV)/(MDL_LAMBDA__EXP__2
     $ *MDL_SW*MDL_SQRT__2)-(MDL_CTZ*MDL_CW*MDL_COMPLEXI*MDL_VEV)
     $ /(MDL_LAMBDA__EXP__2*MDL_SW*MDL_SQRT__2)
      GC_699 = (MDL_CTWI*MDL_VEV)/(MDL_LAMBDA__EXP__2*MDL_SW
     $ *MDL_SQRT__2)-(MDL_CTZI*MDL_CW*MDL_VEV)/(MDL_LAMBDA__EXP__2
     $ *MDL_SW*MDL_SQRT__2)
      GC_815 = -(MDL_CPQM*MDL_CW*MDL_EE*MDL_COMPLEXI*MDL_VEV__EXP__2)
     $ /(2.000000D+00*MDL_LAMBDA__EXP__2*MDL_SW)-(MDL_CPQM*MDL_EE
     $ *MDL_COMPLEXI*MDL_SW*MDL_VEV__EXP__2)/(2.000000D+00*MDL_CW
     $ *MDL_LAMBDA__EXP__2)
      GC_825 = -(MDL_CPT*MDL_CW*MDL_EE*MDL_COMPLEXI*MDL_VEV__EXP__2)
     $ /(2.000000D+00*MDL_LAMBDA__EXP__2*MDL_SW)-(MDL_CPT*MDL_EE
     $ *MDL_COMPLEXI*MDL_SW*MDL_VEV__EXP__2)/(2.000000D+00*MDL_CW
     $ *MDL_LAMBDA__EXP__2)
      GC_315 = MDL_CTLSI1/MDL_LAMBDA__EXP__2-(4.000000D+00*MDL_CTLTI1)
     $ /MDL_LAMBDA__EXP__2-(MDL_CTLS1*MDL_COMPLEXI)/MDL_LAMBDA__EXP__2
     $ +(4.000000D+00*MDL_CTLT1*MDL_COMPLEXI)/MDL_LAMBDA__EXP__2
      GC_316 = -(MDL_CTLTI1/MDL_LAMBDA__EXP__2)-(MDL_CTLT1
     $ *MDL_COMPLEXI)/MDL_LAMBDA__EXP__2
      GC_317 = -(MDL_CTLTI1/MDL_LAMBDA__EXP__2)+(MDL_CTLT1
     $ *MDL_COMPLEXI)/MDL_LAMBDA__EXP__2
      GC_318 = MDL_CTLTI1/MDL_LAMBDA__EXP__2-(MDL_CTLT1*MDL_COMPLEXI)
     $ /MDL_LAMBDA__EXP__2
      GC_319 = MDL_CTLTI1/MDL_LAMBDA__EXP__2+(MDL_CTLT1*MDL_COMPLEXI)
     $ /MDL_LAMBDA__EXP__2
      GC_321 = -(MDL_CTLSI1/MDL_LAMBDA__EXP__2)+(4.000000D+00
     $ *MDL_CTLTI1)/MDL_LAMBDA__EXP__2-(MDL_CTLS1*MDL_COMPLEXI)
     $ /MDL_LAMBDA__EXP__2+(4.000000D+00*MDL_CTLT1*MDL_COMPLEXI)
     $ /MDL_LAMBDA__EXP__2
      GC_516 = (MDL_CQE1*MDL_COMPLEXI)/MDL_LAMBDA__EXP__2
      GC_522 = (MDL_CQLM1*MDL_COMPLEXI)/MDL_LAMBDA__EXP__2
      GC_536 = (MDL_CTE1*MDL_COMPLEXI)/MDL_LAMBDA__EXP__2
      GC_543 = (MDL_CTL1*MDL_COMPLEXI)/MDL_LAMBDA__EXP__2
      END
