ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of dim6top_LO_UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_2 = ', GC_2
      WRITE(*,2) 'GC_3 = ', GC_3
      WRITE(*,2) 'GC_574 = ', GC_574
      WRITE(*,2) 'GC_575 = ', GC_575
      WRITE(*,2) 'GC_580 = ', GC_580
      WRITE(*,2) 'GC_581 = ', GC_581
      WRITE(*,2) 'GC_599 = ', GC_599
      WRITE(*,2) 'GC_600 = ', GC_600
      WRITE(*,2) 'GC_618 = ', GC_618
      WRITE(*,2) 'GC_619 = ', GC_619
      WRITE(*,2) 'GC_644 = ', GC_644
      WRITE(*,2) 'GC_645 = ', GC_645
      WRITE(*,2) 'GC_698 = ', GC_698
      WRITE(*,2) 'GC_699 = ', GC_699
      WRITE(*,2) 'GC_815 = ', GC_815
      WRITE(*,2) 'GC_825 = ', GC_825
      WRITE(*,2) 'GC_315 = ', GC_315
      WRITE(*,2) 'GC_316 = ', GC_316
      WRITE(*,2) 'GC_317 = ', GC_317
      WRITE(*,2) 'GC_318 = ', GC_318
      WRITE(*,2) 'GC_319 = ', GC_319
      WRITE(*,2) 'GC_321 = ', GC_321
      WRITE(*,2) 'GC_516 = ', GC_516
      WRITE(*,2) 'GC_522 = ', GC_522
      WRITE(*,2) 'GC_536 = ', GC_536
      WRITE(*,2) 'GC_543 = ', GC_543
